# Generated by Django 4.2.1 on 2023-06-04 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='fecha_prestamo')),
                ('estado_prestamo', models.IntegerField(choices=[(1, 'entregado'), (2, 'pendiente'), (3, 'reservado')], db_column='estado_prestamo')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('libro', models.ForeignKey(db_column='libro', on_delete=django.db.models.deletion.PROTECT, to='libro.libromodel')),
                ('persona', models.ForeignKey(db_column='persona', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
                'db_table': 'prestamo',
                'managed': True,
            },
        ),
    ]
