# Generated by Django 4.2.1 on 2023-06-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuadernadoModel',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('encuadernado', models.CharField(db_column='encuadernado', max_length=50)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'verbose_name': 'encuadernado',
                'verbose_name_plural': 'encuadernados',
                'db_table': 'encuadernado',
                'managed': True,
            },
        ),
    ]
