# Generated by Django 4.2.1 on 2023-06-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuadernado', '0001_initial'),
        ('editorial', '0001_initial'),
        ('categoria', '0001_initial'),
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=50)),
                ('ejemplares', models.IntegerField(db_column='ejemplares')),
                ('img', models.CharField(db_column='img', max_length=50)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('autor', models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.PROTECT, to='autor.autormodel')),
                ('categoria', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.PROTECT, to='categoria.categoriamodel')),
                ('editorial', models.ForeignKey(db_column='editorial', on_delete=django.db.models.deletion.PROTECT, to='editorial.editorialmodel')),
                ('encuadernado', models.ForeignKey(db_column='encuadernado', on_delete=django.db.models.deletion.PROTECT, to='encuadernado.encuadernadomodel')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'db_table': 'libro',
                'managed': True,
            },
        ),
    ]
